### ISSUE TITLE
DynamicViewDataDictionary support for ViewBag

### ISSUE THREAD

**Issue by rnorbauer** [jlamfers/RazorMachine#35]
In MVC, ViewBags inherit from `DynamicViewDataDictionary`, which means that attempting to call a dynamic property on a ViewBag where that property doesn't exist returns `null` rather than throwing a `RuntimeBinderException` exception.

This allows for very simple syntax in templates like:

```
<title>@( ViewBag.Title ?? "My default title" )</title>
```

Is there any way this functionality can be replicated in Razor Machine?

I am currently writing the equivalent code as the following monstrosity:

```
<title>@( (ViewBag as System.Dynamic.DynamicObject).GetDynamicMemberNames().Contains("Title") ? ViewBag.Title : "My default title")</title>
```

Perhaps I'm missing something?

**Comment by SteveHiner** [comment]
@rnorbauer Did you ever publish your static site generator? I never built a file watcher into mine and reloading the browser on changes could be really handy.

**Comment by emrealdemir** [comment]
It will be a very late response, but i needed same behaviour from my ViewBag dynamic object because of the same reason.

I just expanded the Xipton.Razor.Core.DynamicData class and overrided TryGetValue method as in the following:
```
public class ViewBagDynamic : Xipton.Razor.Core.DynamicData
{
    public override bool TryGetMember(System.Dynamic.GetMemberBinder binder, out object result)
    {
        if (!base.TryGetMember(binder, out result))
        {
            result = null;
        }
        return true;
    }
}
```

If you return true allways and set the `result` outgoing parameter as null when base.TryGetValue result returns false, you get the MVC like behaviour basically.

**Comment by emrealdemir** [comment]
Actually, there is a shortened version of the implementation:
```
public class ViewBagDynamic : Xipton.Razor.Core.DynamicData
{
    public override bool TryGetMember(System.Dynamic.GetMemberBinder binder, out object result)
    {
        base.TryGetMember(binder, out result);
        return true;
    }
}
```

You don't need to check if invocation of base.TryGetMember(binder, out result) returned true or false. If it returns false then it sets `result` parameter as `null`. Then you just need to return `true`.
